### ISSUE TITLE
Feature Suggestion: Readability Improvements

### ISSUE THREAD

**Issue by fly1ngsh33p7** [SpeccyPlays/endlessSkySaveViewer#4]
I think it would be great to have a visualization of a line when hovering above a line.

Also, in my opinion, some cell outlines, at least column lines, would improve readability as well:
![image](https://github.com/SpeccyPlays/endlessSkySaveViewer/assets/28405219/0e132082-680a-4bce-9f2f-da4b81445964)

**Comment by SpeccyPlays** [comment]
Thank you so much for taking the time to look at the site and adding your suggestions !
I've made some tweaks from what you've said and it 's looing better

![image](https://github.com/SpeccyPlays/endlessSkySaveViewer/assets/102996742/6c164d19-6fe8-414e-9a7a-220829331c25)
